# Generated by Django 5.2.8 on 2026-02-01 21:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractUserProfile",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    encrypted_fields.fields.EncryptedEmailField(
                        max_length=255,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="email address",
                    ),
                ),
                (
                    "country_code",
                    encrypted_fields.fields.EncryptedCharField(
                        default="+233", max_length=10
                    ),
                ),
                (
                    "phone_number",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=50, null=True
                    ),
                ),
                (
                    "phone_hmac",
                    models.CharField(db_index=True, editable=False, max_length=128),
                ),
                ("phone_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "updated_at",
                    encrypted_fields.fields.EncryptedDateTimeField(auto_now=True),
                ),
                ("auth_provider", models.CharField(default="email", max_length=255)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "abstractuserprofile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="account.abstractuserprofile",
                    ),
                ),
                (
                    "first_name",
                    encrypted_fields.fields.EncryptedCharField(max_length=255),
                ),
                (
                    "last_name",
                    encrypted_fields.fields.EncryptedCharField(max_length=255),
                ),
                (
                    "role",
                    encrypted_fields.fields.EncryptedCharField(
                        choices=[
                            ("ceo", "CEO"),
                            ("accountant", "Accountant"),
                            ("transport_manager", "Transport Manager"),
                            ("customer", "Customer"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                (
                    "first_name_hash",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                (
                    "last_name_hash",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                (
                    "role_hash",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            bases=("account.abstractuserprofile",),
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=255)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="account.abstractuserprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("ghana_card_id", models.CharField(max_length=50, unique=True)),
                ("occupation", models.CharField(max_length=100)),
                ("gps_address", models.CharField(max_length=255)),
                ("locality", models.CharField(max_length=100)),
                ("town", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("country", models.CharField(default="Ghana", max_length=100)),
                ("join_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("total_bookings", models.IntegerField(default=0)),
                ("total_spent", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "average_rating",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "preferred_vehicle_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("communication_preferences", models.JSONField(default=dict)),
                (
                    "loyalty_tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                ("guarantor_first_name", models.CharField(max_length=100)),
                ("guarantor_last_name", models.CharField(max_length=100)),
                ("guarantor_phone", models.CharField(max_length=20)),
                (
                    "guarantor_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("guarantor_ghana_card_id", models.CharField(max_length=50)),
                ("guarantor_occupation", models.CharField(max_length=100)),
                ("guarantor_gps_address", models.CharField(max_length=255)),
                ("guarantor_relationship", models.CharField(max_length=100)),
                ("guarantor_locality", models.CharField(max_length=100)),
                ("guarantor_town", models.CharField(max_length=100)),
                ("guarantor_city", models.CharField(max_length=100)),
                ("guarantor_region", models.CharField(max_length=100)),
                (
                    "guarantor_country",
                    models.CharField(default="Ghana", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="account_use_first_n_12284b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usersession",
            unique_together={("user", "session_key")},
        ),
    ]
