# Generated by Django 5.2.8 on 2026-02-01 21:23

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
