# Generated by Django 5.2.8 on 2026-02-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_customer_total_spent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="ghana_card_id",
            field=models.CharField(max_length=50),
        ),
    ]
