# Generated by Django 5.2.8 on 2026-02-01 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_customer_ghana_card_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractuserprofile",
            name="email_hash",
            field=models.CharField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                max_length=128,
            ),
            preserve_default=False,
        ),
    ]
