# Generated by Django 5.2.10 on 2026-02-02 02:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_abstractuserprofile_email_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractuserprofile",
            name="country_code_hash",
            field=models.CharField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                max_length=128,
            ),
            preserve_default=False,
        ),
    ]
