# Generated by Django 5.2.10 on 2026-02-16 16:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("car_type", models.CharField(blank=True, max_length=50)),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("color_hex", models.CharField(default="#3B82F6", max_length=7)),
                ("license_plate", models.CharField(max_length=20, unique=True)),
                (
                    "vin",
                    models.CharField(blank=True, max_length=17, null=True, unique=True),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        max_length=20,
                    ),
                ),
                ("seats", models.IntegerField(default=5)),
                ("mileage", models.IntegerField(default=0)),
                ("features", models.JSONField(default=list)),
                ("description", models.TextField(blank=True)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("purchase_date", models.DateField()),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("rented", "Rented"),
                            ("maintenance", "Under Maintenance"),
                            ("insurance_expired", "Insurance Expired"),
                            ("accident", "Accident Damaged"),
                            ("retired", "Retired"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("images", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["make", "model"], name="cars_car_make_3ceb9a_idx"
                    ),
                    models.Index(fields=["status"], name="cars_car_status_3b4442_idx"),
                    models.Index(
                        fields=["license_plate"], name="cars_car_license_fc57d8_idx"
                    ),
                ],
            },
        ),
    ]
