# Generated by Django 5.2.10 on 2026-03-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("rented", "Rented"),
                    ("reserved", "Reserved"),
                    ("extended_booking", "Extended Booking"),
                    ("retired", "Retired"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
