# Generated by Django 5.2.10 on 2026-02-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="car_images/"),
        ),
    ]
