# Generated by Django 5.2.10 on 2026-02-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_car_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="current_value",
        ),
        migrations.RemoveField(
            model_name="car",
            name="daily_rate",
        ),
    ]
