# Generated by Django 5.2.10 on 2026-02-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_remove_car_current_value_remove_car_daily_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="current_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="images",
            field=models.JSONField(default=list),
        ),
    ]
