# Generated by Django 5.2.10 on 2026-02-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_current_value_alter_car_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
