# Generated by Django 5.2.10 on 2026-02-06 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=17)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("driver", "Driver"),
                            ("mechanic", "Mechanic"),
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("casual", "Casual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("day", "Day Shift"),
                            ("night", "Night Shift"),
                            ("flexible", "Flexible"),
                            ("24_hour", "24 Hour"),
                        ],
                        default="day",
                        max_length=20,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("account_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField()),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("driver_license_id", models.CharField(blank=True, max_length=30)),
                ("driver_license_class", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff",
            },
        ),
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.DateField()),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "overtime",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bonuses",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_paid", models.BooleanField(default=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payments",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
            },
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["role", "status"], name="staff_staff_role_5bc3cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["employee_id"], name="staff_staff_employe_f8cd0b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salarypayment",
            unique_together={("staff", "month")},
        ),
    ]
