# Generated by Django 5.2.10 on 2026-02-06 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsurancePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("policy_number", models.CharField(max_length=100, unique=True)),
                ("provider", models.CharField(max_length=200)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("comprehensive", "Comprehensive"),
                            ("third_party", "Third Party"),
                            ("liability", "Liability"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "coverage_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("premium", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "deductible",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("renewal_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("agent_name", models.CharField(blank=True, max_length=200)),
                ("agent_contact", models.CharField(blank=True, max_length=100)),
                ("documents", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_policies",
                        to="cars.car",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Insurance Policies",
            },
        ),
        migrations.CreateModel(
            name="InsuranceRenewal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("previous_end_date", models.DateField()),
                ("new_end_date", models.DateField()),
                ("new_premium", models.DecimalField(decimal_places=2, max_digits=10)),
                ("renewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewals",
                        to="insurance.insurancepolicy",
                    ),
                ),
                (
                    "renewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-renewed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="insurancepolicy",
            index=models.Index(
                fields=["car", "is_current"], name="insurance_i_car_id_06e79b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepolicy",
            index=models.Index(
                fields=["end_date"], name="insurance_i_end_dat_761a6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepolicy",
            index=models.Index(
                fields=["policy_number"], name="insurance_i_policy__526337_idx"
            ),
        ),
    ]
