# Generated by Django 5.2.10 on 2026-02-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="insurancepolicy",
            old_name="coverage_amount",
            new_name="insurance_amount",
        ),
        migrations.RenameField(
            model_name="insurancepolicy",
            old_name="provider",
            new_name="insurance_company",
        ),
        migrations.RemoveField(
            model_name="insurancepolicy",
            name="agent_contact",
        ),
        migrations.RemoveField(
            model_name="insurancepolicy",
            name="agent_name",
        ),
        migrations.RemoveField(
            model_name="insurancepolicy",
            name="deductible",
        ),
        migrations.RemoveField(
            model_name="insurancepolicy",
            name="documents",
        ),
        migrations.RemoveField(
            model_name="insurancepolicy",
            name="premium",
        ),
        migrations.RemoveField(
            model_name="insurancepolicy",
            name="renewal_date",
        ),
    ]
