# Generated by Django 5.2.10 on 2026-02-06 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "insurance",
            "0002_rename_coverage_amount_insurancepolicy_insurance_amount_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insurancerenewal",
            name="new_premium",
        ),
        migrations.AddField(
            model_name="insurancerenewal",
            name="new_insurance_amount",
            field=models.DecimalField(
                decimal_places=2, default=1.0, max_digits=12
            ),
            preserve_default=False,
        ),
    ]
