# Generated by Django 5.2.10 on 2026-02-16 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "__first__"),
        ("customers", "__first__"),
        ("staff", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("pickup_location", models.CharField(blank=True, max_length=500)),
                ("dropoff_location", models.CharField(blank=True, max_length=500)),
                ("special_requests", models.TextField(blank=True)),
                ("is_self_drive", models.BooleanField(default=False)),
                ("driver_license_id", models.CharField(blank=True, max_length=30)),
                ("driver_license_class", models.CharField(blank=True, max_length=10)),
                ("driver_license_issue_date", models.DateField(blank=True, null=True)),
                ("driver_license_expiry_date", models.DateField(blank=True, null=True)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mobile_money", "Mobile Money"),
                            ("pay_in_slip", "Pay-in-Slip"),
                            ("card", "Credit/Debit Card"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("mobile_money_provider", models.CharField(blank=True, max_length=50)),
                ("mobile_money_number", models.CharField(blank=True, max_length=15)),
                (
                    "mobile_money_transaction_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("pay_in_slip_bank", models.CharField(blank=True, max_length=100)),
                ("pay_in_slip_branch", models.CharField(blank=True, max_length=100)),
                ("pay_in_slip_payee", models.CharField(blank=True, max_length=200)),
                ("pay_in_slip_reference", models.CharField(blank=True, max_length=100)),
                ("pay_in_slip_number", models.CharField(blank=True, max_length=100)),
                ("pay_in_slip_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("actual_return_time", models.DateTimeField(blank=True, null=True)),
                ("return_mileage", models.IntegerField(blank=True, null=True)),
                (
                    "late_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="cars.car",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="customers.customer",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "driver"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_bookings",
                        to="staff.staff",
                    ),
                ),
                (
                    "guarantor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.guarantor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["car", "start_date", "end_date"],
                        name="bookings_bo_car_id_a83c2e_idx",
                    ),
                    models.Index(
                        fields=["customer", "status"],
                        name="bookings_bo_custome_0cbf77_idx",
                    ),
                    models.Index(
                        fields=["status", "payment_status"],
                        name="bookings_bo_status_92d418_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="bookings_bo_created_1720a2_idx"
                    ),
                ],
            },
        ),
    ]
