# Generated by Django 5.2.10 on 2026-02-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="driver_license_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="driver_license_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
