# Generated by Django 5.2.10 on 2026-02-16 16:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+233XXXXXXXXX'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "ghana_card_id",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                (
                    "driver_license_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "driver_license_class",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("driver_license_issue_date", models.DateField(blank=True, null=True)),
                ("driver_license_expiry_date", models.DateField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=200)),
                ("gps_address", models.CharField(blank=True, max_length=500)),
                ("address_city", models.CharField(blank=True, max_length=100)),
                ("address_region", models.CharField(blank=True, max_length=100)),
                ("address_country", models.CharField(default="Ghana", max_length=100)),
                (
                    "preferred_vehicle_type",
                    models.CharField(blank=True, max_length=100),
                ),
                ("communication_preferences", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "loyalty_tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_booking_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="customers_c_email_4fdeb3_idx"),
                    models.Index(fields=["phone"], name="customers_c_phone_8493fa_idx"),
                    models.Index(
                        fields=["ghana_card_id"], name="customers_c_ghana_c_da8e60_idx"
                    ),
                    models.Index(
                        fields=["status", "loyalty_tier"],
                        name="customers_c_status_9342f3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Guarantor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+233XXXXXXXXX'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("ghana_card_id", models.CharField(blank=True, max_length=30)),
                ("relationship", models.CharField(blank=True, max_length=100)),
                ("occupation", models.CharField(blank=True, max_length=200)),
                ("gps_address", models.CharField(blank=True, max_length=500)),
                ("address_city", models.CharField(blank=True, max_length=100)),
                ("address_region", models.CharField(blank=True, max_length=100)),
                ("address_country", models.CharField(default="Ghana", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guarantor",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
