# Generated by Django 5.2.10 on 2026-02-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="total_bookings",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="total_spent",
        ),
    ]
